# Generated by Django 5.1.4 on 2024-12-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandresult',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='brandresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='freshnessresult',
            name='id',
        ),
        migrations.AddField(
            model_name='brandresult',
            name='brand',
            field=models.CharField(default='Unknown', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freshnessresult',
            name='freshness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='freshnessresult',
            name='item_name',
            field=models.AutoField(default='Unknown', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freshnessresult',
            name='shelf_life',
            field=models.IntegerField(default=1),
        ),
    ]
