# Generated by Django 5.1.4 on 2024-12-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_freshnessresult_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandresult',
            name='brand',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='freshnessresult',
            name='item_name',
            field=models.CharField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='freshnessresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
